#!/usr/bin/env sh

src_dir="$( cd -- "$(dirname "$0" )" >/dev/null 2>&1 ; pwd -P )"
target_dir="$HOME"

# For every file that should be linked into ~
(cd $src_dir && find * -type f -not -path 'data/*') | while read -r file ; do

    dirpath="$(dirname $file)"

    # Check if the file is listed in .linkignore
    # if grep -q "^$dirpath/$filename$" "$src_dir/.linkignore"; then
    #     echo "Ignoring $dirpath/$filename"
    #     continue
    # fi

    # Create the target directory if it doesn't exist
    mkdir -p "$target_dir/.$dirpath"

    # Create a symlink from the source file to the target directory
    ln -s "$src_dir/$file" "$target_dir/.$file"
done

# Link vimrc to nvim rc file
(cd $target_dir && ln -s $src_dir/config/nvim/init.vim .vimrc)

# for installer in ~/.installers/*-inst; do
# 	source $installer
# done

