#!/usr/bin/env bash

# re-alias ls commands to use the G flag, which enables color output on macos
alias ll="ls -GAlF"
alias la='ls -Ga'
alias l="ls -Gl"
alias ls="ls -G"

if command -v colordiff
	alias diff=colordiff
else
	alias diff=diff # Cancel diff --color alias in .commonrc
fi
