#!/usr/bin/env bash

# re-alias ls commands to use the G flag, which enables color output on macos
alias ll="ls -GAlF"
alias la='ls -Ga'
alias l="ls -Gl"
alias ls="ls -G"

# diff --color not supported on macos
# Replace diff --color alias from .commonrc
if command -v colordiff &> /dev/null
then
    alias diff=colordiff
else
    alias diff=diff # Cancel diff --color alias in .commonrc
fi

# iPython convenient alias
alias ipython="python3 -m IPython"
