#!/usr/bin/env bash

# Windows clipboard copy and paste
alias wclip=clip.exe
alias wpaste="powershell.exe Get-Clipboard"

# Windows XMing startup and stop commands
xming() {
	if [[ $# -ne 1 ]]; then
		echo "usage: xming start|stop|status"
		echo "Starts/stops/reports status of the xming daemon on the host windows machine."
	elif [[ $1 == "start" ]]; then
		powershell.exe "& 'C:\Program Files (x86)\Xming\Xming.exe' -multiwindow -clipboard -ac"
		# Configure display for Windows host's X server
		export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0
	elif [[ $1 == "stop" ]]; then
		powershell.exe "Get-Process -Name XMing |Stop-Process"
		export DISPLAY=""
	elif [[ $1 == "status" ]]; then
		if [[ -n $DISPLAY ]]; then
			echo "xming is running. DISPLAY=$DISPLAY"
		else
			echo "xming is not running."
		fi
	fi
}

# Powerline configuration
if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  source /usr/share/powerline/bindings/bash/powerline.sh
fi

# Change other-writable directories to be orange instead of green-highlighted
# Useful on wsl because many windows directories are modeled as other-writable
LS_COLORS=$LS_COLORS'ow=33:'

# beep via powershell
_beep() {
    powershell.exe "[console]::beep($1,$2)"
}
alias beep="_beep 1800 300"


### WSL DEFAULTS ###

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac
